"""add timestamps to expenses

Revision ID: 336b86bc48d7
Revises: 
Create Date: 2025-11-03 01:21:52.890582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '336b86bc48d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.drop_constraint(op.f('expenses_user_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_user_id_fkey'), 'expenses', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('expenses', 'updated_at')
    # ### end Alembic commands ###
