"""add composite indexes for expenses

Revision ID: deb65e1cf6e2
Revises: 4c2fbf924f60
Create Date: 2025-11-03 17:02:38.021663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb65e1cf6e2'
down_revision: Union[str, Sequence[str], None] = '4c2fbf924f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_user_category_created'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_user_created'), table_name='expenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expenses_user_created'), 'expenses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_expenses_user_category_created'), 'expenses', ['user_id', 'category', 'created_at'], unique=False)
    # ### end Alembic commands ###
