"""add composite indexes for expenses

Revision ID: fe9aa023fe96
Revises: 336b86bc48d7
Create Date: 2025-11-03 08:26:06.268084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9aa023fe96'
down_revision: Union[str, Sequence[str], None] = '336b86bc48d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expenses_user_category', 'expenses', ['user_id', 'category'], unique=False)
    op.create_index('ix_expenses_user_created_at', 'expenses', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_user_created_at', table_name='expenses')
    op.drop_index('ix_expenses_user_category', table_name='expenses')
    # ### end Alembic commands ###
